---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [3]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [4]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    
    return df.iloc[0]

# You can examine what your ftvunction returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()



# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [5]:
def answer_one():
    m = 0
    i = 0
       
    for con,i in zip(df["Gold"],df.index):
            if(con>=m):
                m = con
                ans = i
            
    return ans
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [4]:
def answer_two():
    m = 0
    df["Country"] = df.index
    for con in df["Country"]:
        #print(df.loc[con]["# Summer"])
        if(abs(df.loc[con]["Gold"] - df.loc[con]["Gold.1"])>=m):
            m = abs(df.loc[con]["Gold"] - df.loc[con]["Gold.1"])
            ans = con
            
    return ans
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [4]:
def answer_three():
    df["Country"] = df.index
    m = 0
    
    for con in df["Country"]:
        if(df.loc[con]['Gold'] >=1 and df.loc[con]['Gold.1']>=1):
            if(abs(df.loc[con]['Gold'] - df.loc[con]['Gold.1'])/df.loc[con]['Gold.2'] >= m):
                m = abs(df.loc[con]['Gold'] - df.loc[con]['Gold.1'])/df.loc[con]['Gold.2']
                ans = con
    return ans
    '''elegible = data[(data.>=1) & (data.winter_gold>=1)]
    ratios = (elegible.summer_gold - elegible.winter_gold).abs()/elegible.total_gold
    return ratios.argmax()'''
answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created.

*This function should return a Series named `Points` of length 146*

In [6]:
import pandas as pd
import numpy
def answer_four():
    pt = []
    df["Country"] = df.index
    ans = 0
    for con in df["Country"]:
        
        if(df.loc[con]["Gold.2"]>=0):
             ans = ans + 3 * df.loc[con]["Gold.2"]
        if(df.loc[con]["Silver.2"]>=0):
            ans = ans + 2 * df.loc[con]["Silver.2"]
        if(df.loc[con]["Bronze.2"]>=0):
            ans = ans + 1 * df.loc[con]["Bronze.2"]
        pt.append(ans)    
    Points = pd.Series(pt)#index = df.index)
    
    
    '''print(len(Points))
    points = numpy.zeros(len(df))
    points += df['Gold.2']* 3
    points += df['Silver.2'] * 2
    points += df['Bronze.2']
    return pd.Series(points, index=df.index)
Points = answer_four()
#assert Points.loc["United States"] == 5684'''
    return Points
answer_four()

0          2
1         29
2        159
3        175
4        197
5       1120
6       1689
7       1732
8       1756
9       1757
10      1758
11      1912
12      2188
13      2189
14      2194
15      2196
16      2380
17      2382
18      2793
19      2796
20      2808
21      3654
22      3678
23      4798
24      4827
25      4834
26      4836
27      4903
28      5323
29      5325
       ...  
116    26428
117    26432
118    26434
119    26438
120    27655
121    28285
122    28291
123    28323
124    28327
125    28331
126    28375
127    28376
128    28378
129    28405
130    28424
131    28615
132    28629
133    28849
134    28852
135    34536
136    34552
137    34590
138    34608
139    34612
140    34614
141    34785
142    34789
143    34792
144    34810
145    34848
dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov/popest/data/counties/totals/2015/CO-EST2015-alldata.html). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](http://www.census.gov/popest/data/counties/totals/2015/files/CO-EST2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [9]:
import pandas as pd
def answer_five():
    census_df = pd.read_csv('census.csv')
    return census_df.groupby(["STNAME"],sort=False).sum()["COUNTY"].idxmax()
answer_five()

'Texas'

### Question 6
Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [13]:
import pandas as pd
census_df = pd.read_csv('census.csv')
class CensusVariables:
    state = "STNAME"
    county = "CTYNAME"
    census_population = "CENSUS2010POP"
    region = "REGION"
    population_estimate = ["POPESTIMATE2010",
                           "POPESTIMATE2011",
                           "POPESTIMATE2012",
                           "POPESTIMATE2013",
                           "POPESTIMATE2014",
                           "POPESTIMATE2015"]
    county_level = 50 
    summary_level = "SUMLEV"
cv = CensusVariables()
counties = census_df[census_df[cv.summary_level] == cv.county_level]
counties = counties.reset_index()
counties_original_index = census_df[census_df[
    cv.summary_level]==cv.county_level]
def answer_six():
    #t_t = counties[cv.census_population].nlargest(3)
    #print(t_t)
    top_three = counties.groupby(cv.state)[cv.census_population].nlargest(3)
    #print(top_three)
    states = top_three.groupby(level = 0).sum()
    
    return list(states.nlargest(3).index)
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [17]:
import pandas as pd
#def f_change(c_df):
    
def answer_seven():
    return counties.iloc[
	(counties[
	    cv.population_estimate].max(axis=1) -
	 counties[
	     cv.population_estimate].min(axis=1)
	).argmax()][cv.county]

answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [16]:
def answer_eight():
    return
    
answer_eight()    